### ISSUE TITLE
TypeError: discord_js_1.IntentsBitField is not a constructor

### ISSUE THREAD

**Issue by ejsupernova** [scratch-for-discord/scratch-for-discord#231]
TypeError: discord_js_1.IntentsBitField is not a constructor
im getting this on my discord bot heres the full thing
Error!
TypeError: discord_js_1.IntentsBitField is not a constructor
    at C:\Average bot for aiden\Untitled document\node_modules\discord-logs\lib\index.js:18:21
    at Generator.next (<anonymous>)
    at C:\Average bot for aiden\Untitled document\node_modules\discord-logs\lib\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Average bot for aiden\Untitled document\node_modules\discord-logs\lib\index.js:4:12)
    at module.exports (C:\Average bot for aiden\Untitled document\node_modules\discord-logs\lib\index.js:14:39)
    at C:\Average bot for aiden\Untitled document\index.js:83:5
    at Object.<anonymous> (C:\Average bot for aiden\Untitled document\index.js:135:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)

**Comment by nekoify** [comment]
Run `npm i discord-logs@2.0.0` in shell to fix

**Comment by Malix-Labs** [comment]
Not an issue
